# Generated by Django 4.2.16 on 2024-11-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('AccountID', models.AutoField(primary_key=True, serialize=False, verbose_name='账号ID')),
                ('telephone', models.CharField(max_length=15, unique=True, verbose_name='电话')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否管理员')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
